### ISSUE TITLE
Feature Request: Auto close links that open in new tabs

### ISSUE THREAD

**Issue by poopfarts1** [Citrinate/gleamHelper#1]
Hi there, I was wondering if there might be a way you could add a feature where the script will automatically close the new tabs that get opened when you click on a "visit this link" task, or perhaps just make the system think that the link has been clicked so you can complete the task without having to mess with the tabs. Also, if this feature could be toggled on an off that would be great. I love your script and I think this addition would make it perfect! Thanks for all your hard work, man!

**Comment by Citrinate** [comment]
Been going back and forth over whether or not this feature would be appropriate for this script, and ultimately I've decided against it.  I'm just not comfortable with adding anything that would change how a Gleam.io giveaways works.

**Comment by poopfarts1** [comment]
Fair enough, makes sense.
