### ISSUE TITLE
Move continue to task button

### ISSUE THREAD

**Issue by Wrascon** [Citrinate/gleamHelper#3]
I remember that earlier Gleam with group tasks were simple. If it composed, then the task confirmed. How about to return the old method? Window with the group should not appear to click on the "continue" button, and need to remove it, while button "Сontinue" replace to the task icon "?" for actions in one click.
As a result, all of the tasks "?" will be "Continue", and the button to join the group already has left of her.

**Comment by Citrinate** [comment]
It's possible, but I feel the same way here as I do about a previous request: https://github.com/Citrinate/gleamHelper/issues/1#issuecomment-210028879

**Comment by Wrascon** [comment]
I did not see it. Maybe it was necessary to open a previous request and add a new message, rather than open a new discus here. In any case, thanks for the answer
