### ISSUE TITLE
show the answer for the question

### ISSUE THREAD

**Issue by abccbaandy** [Citrinate/gleamHelper#4]
hi, can you add a "hint" for these question?

some giveway need a answer, and we need do something like this.
http://iandrohackerdk.blogspot.tw/2016/02/gleamio-giveaway-cheating-how-to-get.html

btw, don't put the answer in the input box, so afraid get ban:(

thx

**Comment by Citrinate** [comment]
I don't have plans to do this.  Even showing the answer might be a bit iffy; it would be a departure from the types of improvements this script already provides.

Adding it to this script would make abuse of the workaround you linked to easier and more widespread.  There's the concern that they could patch the workaround under those conditions.
