### ISSUE TITLE
Twitch API needs updating

### ISSUE THREAD

**Issue by TizianoVecellio** [Citrinate/gleamHelper#5]
The Twitch API got updated and now the Twitch integration in the script doesn't work.

**Comment by DFNCTSC** [comment]
👍 

Following on Twitch & checking for subscription status still work but the most important **Unfollowing on Twitch doesn't work**.

@Citrinate please don't forsake us. 😄

**Comment by Citrinate** [comment]
I just tested the "Unfollow", "Delete Retweet", and "Delete Tweet" functionality, but was unable to reproduce these types of errors.

I did find a new type of Twitter action called "twitter_hashtags", which has you sending out a Tweet through a popup box.  A new version has been released, v1.2.1, which adds support for this action type.

**Comment by TizianoVecellio** [comment]
Twitter was never a problem, Twitch was. Unfollowing on twitch doesn't work. "Gleam.helper Error: Failed to unfollow Twitch user: xxx".

**Comment by DFNCTSC** [comment]
@Citrinate As @TizianoVecellio has pointed out what we already said: Twitter is not the problem, it's Twitch. **twitch.tv**

Thanks for all your time and help. <3

**Comment by Citrinate** [comment]
My bad, thanks for correcting me.

v1.2.2 has been released to address the changes to the Twitch API.

**Comment by DFNCTSC** [comment]
Thanks so much Citrinate! ❤️

**Comment by TizianoVecellio** [comment]
Thanks man, really appreciate it.
